baseURL = "https://paxno.github.io/AIcoach/"
languageCode = "zh-CN"
title = "AIcoach 导航"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true

[params]
    author = "AIcoach"
    description = "AIcoach 网址导航 | 收集AI相关的优质网站"
    siteurl = "https://paxno.github.io/AIcoach/"
    repository = "https://github.com/paxno/AIcoach"
    keywords = "AIcoach,网址导航,AI导航,人工智能"
    
    # Logo 设置
    favicon = "/favicon.png"         # 网站图标
    images = 
        favicon = "assets/images/favicon.png"
        logo = "assets/images/logo@2x.png"
        logo_dark = "assets/images/logo_dark@2x.png"
    
[params.search]
    enable = true
    
[params.darkmode]
    enable = true    # 启用深色模式切换功能

[taxonomies]
    category = "categories"
    tag = "tags"
